### ISSUE TITLE
Computing jitter in MS in NDT7 vs NDT5

### ISSUE THREAD

**Issue by helfrichmichael** [m-lab/ndt7-js#21]
Hi,

In NDT5's implementation, there was a MinRTT and MaxRTT value available. In NDT5, jitter is equal to MaxRTT - MinRTT [see here](https://github.com/m-lab/mlab-speedtest/blob/2019-11-11/app/assets/js/ndt-wrapper.js#L190). 

In the response for NDT7, I see MinRTT in the `data.LastServerMeasurement.BBRInfo.MinRTT` and `data.LastServerMeasurement.BBRInfo.MinRTT`, but I do not see a MaxRTT (see the TCPInfo object below).
![image](https://user-images.githubusercontent.com/9116898/110976236-aa126a80-832e-11eb-9bc6-a8baf5cda035.png)

I'm curious if the MaxRTT value was renamed or if there is a better way of establishing jitter in ms for the client. If I take the RTT - MinRTT for example, the value doesn't seem to align with jitter values from NDT5.

**Comment by critzo** [comment]
Hello @helfrichmichael . Thanks for raising this question. In NDT5, a calculation of approximate jitter was accomplished using the method you describe. In NDT7, we recommend using RTTVar (Round Trip Time Variation). If helpful, this support FAQ also describes these differences with respect to NDT generally, and issues of different definitions of jitter from different communities: https://support.measurementlab.net/help/en-us/4-ndt-network-diagnostic-tool/13-how-do-the-different-ndt-protocols-report-jitter

**Comment by helfrichmichael** [comment]
@critzo perfect, thanks for the quick assistance! I assume that I'd just divide by 1000 to convert this to a pure millisecond value.

**Comment by critzo** [comment]
@helfrichmichael I believe so, but could you confirm @stephen-soltesz ?

Also, we were discussing this on a team chat, and some more details about RTTVar were discussed. 

RTTVar is measured and used by TCP as specified by RFC 6298. Over the course of the test, TCP measurements are captured as snapshots which are all saved in the raw test data. In BigQuery, the final value in the measurement result row is the last computed value of RTTVar by the server kernel for the test.  Just to note that in the BQ row, and the value presented back to the client, is this last value. 

The team will likely discuss the feasibility of and RTTVar metric that is computed over the entirety of a test in the future. This would require some changes to our parser for getting that value into the BigQuery result, and different plumbing on the server side to provide this back to the user at test runtime.

**Comment by stephen-soltesz** [comment]
@helfrichmichael yes, RTTVar/1000 would be milliseconds.

For your use case, this is the right variable.

@critzo's comment is acknowledging that the calculation of RTTVar is updated by the kernel over the lifetime of the connection, and you're using the final value.

The ndt7 protocol sends some of the intermediate tcpinfo snapshots to the client over the life of the connection, however that's not necessary. In fact, afaik, none of our own reference clients use that data other than to log it.

**Comment by helfrichmichael** [comment]
Thanks for the additional context @critzo and @stephen-soltesz. Really appreciate the quick responses and follow-up. I've got my client implementation wrapped up I think thanks to this :).

**Comment by laiyi-ohlsen** [comment]
Resolving, @helfrichmichael let us know if you need further assistance!
