### ISSUE TITLE
upload measurements reported results over link capacity

### ISSUE THREAD

**Issue by critzo** [m-lab/ndt7-js#22]
Users have reported upload measurements over the capacity of their links, for example this report from a user in Amsterdam:
![image](https://user-images.githubusercontent.com/4633345/111991860-26edd300-8aeb-11eb-8e80-028c3854bf93.png)

Additional details:

> Laptop: modern HP, Win 10 Enterprise, Wifi connected (n or ac), mesh wifi home network (AVM Fritz gear)
> Browsers: Chrome , Firefox, latest, only adblock and privacy enhancing extensions – results are very similar between these.
> ISP connection: VDSL (no pair bonding) ; ISP is Freedom Internet.

**Comment by bassosimone** [comment]
I have seen this happening in the past when the connection was closed by the browser because of some resources limit and the only available data point was really towards the beginning of the trace, so it was insanely high.

**Comment by critzo** [comment]
@bassosimone no, we do not.

**Comment by robertodauria** [comment]
I think we fixed this with https://github.com/m-lab/ndt7-js/pull/45. It's an effect of sending too much data at the beginning of the upload phase, the websocket connection terminates early and what is shown is the latest client-side measurement. It could be replicated 100% of the time on Safari/OSX, but this is the first time I see it in a different environment. Please feel free to reopen if users report this is still happening.
