### ISSUE TITLE
provide an html / JS example with & without use of callback functions

### ISSUE THREAD

**Issue by critzo** [m-lab/ndt7-js#7]

**Comment by critzo** [comment]
Just noting that the README references that an example web client is provided, bu it's the node-js client. The NDT spec links to a basic client that could be used as a starting point: https://github.com/bassosimone/ndt7-server-go-minimal/blob/master/static/index.html

**Comment by glennfish** [comment]
While I can't contribute I am definitely interested in the HTML / JS example.  If possible, with Ping and Jitter as well.  Would be willing to pay for a working prototype yet leave the result in the public domain.

**Comment by robertodauria** [comment]
Closed by https://github.com/m-lab/ndt7-js/pull/55
